<?php

namespace Database\Seeders\Tenant;

use Illuminate\Database\Seeder;
use Silber\Bouncer\BouncerFacade as Bouncer;

class BouncerRolesSeeder extends Seeder
{
    public function run(): void
    {
        $roles = [
            ['name' => 'root', 'title' => 'Root', 'priority' => 9],
            ['name' => 'admin', 'title' => 'Administrador', 'priority' => 2],
        ];

        foreach ($roles as $role) {
            Bouncer::role()->updateOrCreate(['name' => $role['name']], $role);
        }

        Bouncer::allow('root')->everything();
        Bouncer::allow('admin')->to([
            'roles.access',
            'roles.save',
            'users.view',
            'users.add',
            'users.edit',
            'users.delete',
            'users.permissions',
            'settings.save',
            'products.view',
            'products.add',
            'products.edit',
            'products.delete',
            'pieces.view',
            'pieces.add',
            'pieces.edit',
            'pieces.delete',
            'materials.view',
            'materials.add',
            'materials.edit',
            'materials.delete',
            'suppliers.view',
            'suppliers.add',
            'suppliers.edit',
            'suppliers.delete',
            'manufacturers.view',
            'manufacturers.add',
            'manufacturers.edit',
            'manufacturers.delete',
            'material_suppliers.view',
            'material_suppliers.add',
            'material_suppliers.edit',
            'material_suppliers.delete',
            'material_supplier_prices.view',
            'material_supplier_prices.add',
            'material_supplier_prices.edit',
            'material_supplier_prices.delete',
            'product_pieces.view',
            'product_pieces.add',
            'product_pieces.edit',
            'product_pieces.delete',
            'piece_materials.view',
            'piece_materials.add',
            'piece_materials.edit',
            'piece_materials.delete',
            'entities.view',
            'entities.add',
            'entities.edit',
            'entities.delete',
            'contact_data.view',
            'contact_data.add',
            'contact_data.edit',
            'contact_data.delete',
            'clients.view',
            'clients.add',
            'clients.edit',
            'clients.delete',
            'orders.view',
            'orders.add',
            'orders.edit',
            'orders.delete',
            'orders.checkout',
            'order_concepts.view',
            'order_concepts.add',
            'order_concepts.edit',
            'order_concepts.delete',
            'order_pieces.view',
            'order_pieces.add',
            'order_pieces.edit',
            'order_pieces.delete',
            'order_piece_statuses.view',
            'order_piece_statuses.add',
            'order_piece_statuses.edit',
            'order_piece_statuses.delete',
            'production_orders.view',
            'production_orders.add',
            'production_orders.edit',
            'production_orders.delete',
            'manufacturer_pieces_cost.view',
            'manufacturer_pieces_cost.add',
            'manufacturer_pieces_cost.edit',
            'manufacturer_pieces_cost.delete',
            'manufacturer_order_pieces.view',
            'manufacturer_order_pieces.add',
            'manufacturer_order_pieces.edit',
            'manufacturer_order_pieces.delete',
            'manufacturing_follow_up.view',
            'manufacturing_follow_up.add',
            'manufacturing_follow_up.edit',
            'manufacturing_follow_up.delete',
            'carriers.view',
            'carriers.add',
            'carriers.edit',
            'carriers.delete',
            'carrier_units.view',
            'carrier_units.add',
            'carrier_units.edit',
            'carrier_units.delete',
            'drivers.view',
            'drivers.add',
            'drivers.edit',
            'drivers.delete',
            'shipments.view',
            'shipments.add',
            'shipments.edit',
            'shipments.delete',
            'shipment_order_pieces.view',
            'shipment_order_pieces.add',
            'shipment_order_pieces.edit',
            'shipment_order_pieces.delete',
            'shipment_drivers.view',
            'shipment_drivers.add',
            'shipment_drivers.edit',
            'shipment_drivers.delete',
            'shipment_routes.view',
            'shipment_routes.add',
            'shipment_routes.edit',
            'shipment_routes.delete',
            'entity_addresses.view',
            'entity_addresses.add',
            'entity_addresses.edit',
            'entity_addresses.delete',
        ]);
    }
}
